# Generated by Django 4.0.3 on 2022-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_vote_voter_delete_votemachine_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_distict',
            field=models.IntegerField(default=0),
        ),
    ]
