# Generated by Django 4.0.3 on 2022-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_voter_vote_distict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='vote_distict',
        ),
    ]
